spring:
  datasource:
    url: 
    username: 
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  messages:
    basename: messages
  security:
    secret-key:
mybatis:
  mapper-locations:
    - classpath*:/db/mybatis/mapper/*.xml
    - classpath*:/db/mybatis/mapper/extension/*.xml