package work.tomosse.model.db;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AccountExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table account
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table account
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table account
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public AccountExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table account
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("password is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("password is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("password =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("password <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("password >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("password >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("password <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("password <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("password like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("password not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("password in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("password not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("password between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("password not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andApi_tokenIsNull() {
			addCriterion("api_token is null");
			return (Criteria) this;
		}

		public Criteria andApi_tokenIsNotNull() {
			addCriterion("api_token is not null");
			return (Criteria) this;
		}

		public Criteria andApi_tokenEqualTo(String value) {
			addCriterion("api_token =", value, "api_token");
			return (Criteria) this;
		}

		public Criteria andApi_tokenNotEqualTo(String value) {
			addCriterion("api_token <>", value, "api_token");
			return (Criteria) this;
		}

		public Criteria andApi_tokenGreaterThan(String value) {
			addCriterion("api_token >", value, "api_token");
			return (Criteria) this;
		}

		public Criteria andApi_tokenGreaterThanOrEqualTo(String value) {
			addCriterion("api_token >=", value, "api_token");
			return (Criteria) this;
		}

		public Criteria andApi_tokenLessThan(String value) {
			addCriterion("api_token <", value, "api_token");
			return (Criteria) this;
		}

		public Criteria andApi_tokenLessThanOrEqualTo(String value) {
			addCriterion("api_token <=", value, "api_token");
			return (Criteria) this;
		}

		public Criteria andApi_tokenLike(String value) {
			addCriterion("api_token like", value, "api_token");
			return (Criteria) this;
		}

		public Criteria andApi_tokenNotLike(String value) {
			addCriterion("api_token not like", value, "api_token");
			return (Criteria) this;
		}

		public Criteria andApi_tokenIn(List<String> values) {
			addCriterion("api_token in", values, "api_token");
			return (Criteria) this;
		}

		public Criteria andApi_tokenNotIn(List<String> values) {
			addCriterion("api_token not in", values, "api_token");
			return (Criteria) this;
		}

		public Criteria andApi_tokenBetween(String value1, String value2) {
			addCriterion("api_token between", value1, value2, "api_token");
			return (Criteria) this;
		}

		public Criteria andApi_tokenNotBetween(String value1, String value2) {
			addCriterion("api_token not between", value1, value2, "api_token");
			return (Criteria) this;
		}

		public Criteria andRoleIsNull() {
			addCriterion("role is null");
			return (Criteria) this;
		}

		public Criteria andRoleIsNotNull() {
			addCriterion("role is not null");
			return (Criteria) this;
		}

		public Criteria andRoleEqualTo(String value) {
			addCriterion("role =", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleNotEqualTo(String value) {
			addCriterion("role <>", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleGreaterThan(String value) {
			addCriterion("role >", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleGreaterThanOrEqualTo(String value) {
			addCriterion("role >=", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleLessThan(String value) {
			addCriterion("role <", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleLessThanOrEqualTo(String value) {
			addCriterion("role <=", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleLike(String value) {
			addCriterion("role like", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleNotLike(String value) {
			addCriterion("role not like", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleIn(List<String> values) {
			addCriterion("role in", values, "role");
			return (Criteria) this;
		}

		public Criteria andRoleNotIn(List<String> values) {
			addCriterion("role not in", values, "role");
			return (Criteria) this;
		}

		public Criteria andRoleBetween(String value1, String value2) {
			addCriterion("role between", value1, value2, "role");
			return (Criteria) this;
		}

		public Criteria andRoleNotBetween(String value1, String value2) {
			addCriterion("role not between", value1, value2, "role");
			return (Criteria) this;
		}

		public Criteria andCreated_atIsNull() {
			addCriterion("created_at is null");
			return (Criteria) this;
		}

		public Criteria andCreated_atIsNotNull() {
			addCriterion("created_at is not null");
			return (Criteria) this;
		}

		public Criteria andCreated_atEqualTo(Date value) {
			addCriterion("created_at =", value, "created_at");
			return (Criteria) this;
		}

		public Criteria andCreated_atNotEqualTo(Date value) {
			addCriterion("created_at <>", value, "created_at");
			return (Criteria) this;
		}

		public Criteria andCreated_atGreaterThan(Date value) {
			addCriterion("created_at >", value, "created_at");
			return (Criteria) this;
		}

		public Criteria andCreated_atGreaterThanOrEqualTo(Date value) {
			addCriterion("created_at >=", value, "created_at");
			return (Criteria) this;
		}

		public Criteria andCreated_atLessThan(Date value) {
			addCriterion("created_at <", value, "created_at");
			return (Criteria) this;
		}

		public Criteria andCreated_atLessThanOrEqualTo(Date value) {
			addCriterion("created_at <=", value, "created_at");
			return (Criteria) this;
		}

		public Criteria andCreated_atIn(List<Date> values) {
			addCriterion("created_at in", values, "created_at");
			return (Criteria) this;
		}

		public Criteria andCreated_atNotIn(List<Date> values) {
			addCriterion("created_at not in", values, "created_at");
			return (Criteria) this;
		}

		public Criteria andCreated_atBetween(Date value1, Date value2) {
			addCriterion("created_at between", value1, value2, "created_at");
			return (Criteria) this;
		}

		public Criteria andCreated_atNotBetween(Date value1, Date value2) {
			addCriterion("created_at not between", value1, value2, "created_at");
			return (Criteria) this;
		}

		public Criteria andUpdated_atIsNull() {
			addCriterion("updated_at is null");
			return (Criteria) this;
		}

		public Criteria andUpdated_atIsNotNull() {
			addCriterion("updated_at is not null");
			return (Criteria) this;
		}

		public Criteria andUpdated_atEqualTo(Date value) {
			addCriterion("updated_at =", value, "updated_at");
			return (Criteria) this;
		}

		public Criteria andUpdated_atNotEqualTo(Date value) {
			addCriterion("updated_at <>", value, "updated_at");
			return (Criteria) this;
		}

		public Criteria andUpdated_atGreaterThan(Date value) {
			addCriterion("updated_at >", value, "updated_at");
			return (Criteria) this;
		}

		public Criteria andUpdated_atGreaterThanOrEqualTo(Date value) {
			addCriterion("updated_at >=", value, "updated_at");
			return (Criteria) this;
		}

		public Criteria andUpdated_atLessThan(Date value) {
			addCriterion("updated_at <", value, "updated_at");
			return (Criteria) this;
		}

		public Criteria andUpdated_atLessThanOrEqualTo(Date value) {
			addCriterion("updated_at <=", value, "updated_at");
			return (Criteria) this;
		}

		public Criteria andUpdated_atIn(List<Date> values) {
			addCriterion("updated_at in", values, "updated_at");
			return (Criteria) this;
		}

		public Criteria andUpdated_atNotIn(List<Date> values) {
			addCriterion("updated_at not in", values, "updated_at");
			return (Criteria) this;
		}

		public Criteria andUpdated_atBetween(Date value1, Date value2) {
			addCriterion("updated_at between", value1, value2, "updated_at");
			return (Criteria) this;
		}

		public Criteria andUpdated_atNotBetween(Date value1, Date value2) {
			addCriterion("updated_at not between", value1, value2, "updated_at");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table account
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table account
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 19 18:58:53 JST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}