package work.tomosse.model.db;

import java.util.Date;

public class Account {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.id
	 * @mbg.generated  Tue Nov 19 20:22:34 JST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.name
	 * @mbg.generated  Tue Nov 19 20:22:34 JST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.password
	 * @mbg.generated  Tue Nov 19 20:22:34 JST 2019
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.api_token
	 * @mbg.generated  Tue Nov 19 20:22:34 JST 2019
	 */
	private String api_token;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.role
	 * @mbg.generated  Tue Nov 19 20:22:34 JST 2019
	 */
	private String role;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.created_at
	 * @mbg.generated  Tue Nov 19 20:22:34 JST 2019
	 */
	private Date created_at;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.updated_at
	 * @mbg.generated  Tue Nov 19 20:22:34 JST 2019
	 */
	private Date updated_at;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.id
	 * @return  the value of account.id
	 * @mbg.generated  Tue Nov 19 20:22:34 JST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.id
	 * @param id  the value for account.id
	 * @mbg.generated  Tue Nov 19 20:22:34 JST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.name
	 * @return  the value of account.name
	 * @mbg.generated  Tue Nov 19 20:22:34 JST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.name
	 * @param name  the value for account.name
	 * @mbg.generated  Tue Nov 19 20:22:34 JST 2019
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.password
	 * @return  the value of account.password
	 * @mbg.generated  Tue Nov 19 20:22:34 JST 2019
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.password
	 * @param password  the value for account.password
	 * @mbg.generated  Tue Nov 19 20:22:34 JST 2019
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.api_token
	 * @return  the value of account.api_token
	 * @mbg.generated  Tue Nov 19 20:22:34 JST 2019
	 */
	public String getApi_token() {
		return api_token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.api_token
	 * @param api_token  the value for account.api_token
	 * @mbg.generated  Tue Nov 19 20:22:34 JST 2019
	 */
	public void setApi_token(String api_token) {
		this.api_token = api_token == null ? null : api_token.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.role
	 * @return  the value of account.role
	 * @mbg.generated  Tue Nov 19 20:22:34 JST 2019
	 */
	public String getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.role
	 * @param role  the value for account.role
	 * @mbg.generated  Tue Nov 19 20:22:34 JST 2019
	 */
	public void setRole(String role) {
		this.role = role == null ? null : role.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.created_at
	 * @return  the value of account.created_at
	 * @mbg.generated  Tue Nov 19 20:22:34 JST 2019
	 */
	public Date getCreated_at() {
		return created_at;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.created_at
	 * @param created_at  the value for account.created_at
	 * @mbg.generated  Tue Nov 19 20:22:34 JST 2019
	 */
	public void setCreated_at(Date created_at) {
		this.created_at = created_at;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.updated_at
	 * @return  the value of account.updated_at
	 * @mbg.generated  Tue Nov 19 20:22:34 JST 2019
	 */
	public Date getUpdated_at() {
		return updated_at;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.updated_at
	 * @param updated_at  the value for account.updated_at
	 * @mbg.generated  Tue Nov 19 20:22:34 JST 2019
	 */
	public void setUpdated_at(Date updated_at) {
		this.updated_at = updated_at;
	}
}