package work.tomosse.model.db;

import java.util.Date;

public class AccountProduct {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account_product.id
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account_product.permission
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	private Integer permission;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account_product.account_id
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	private Long account_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account_product.product_id
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	private Long product_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account_product.created_by
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	private Long created_by;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account_product.updated_by
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	private Long updated_by;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account_product.created_at
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	private Date created_at;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account_product.updated_at
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	private Date updated_at;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account_product.id
	 * @return  the value of account_product.id
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account_product.id
	 * @param id  the value for account_product.id
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account_product.permission
	 * @return  the value of account_product.permission
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public Integer getPermission() {
		return permission;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account_product.permission
	 * @param permission  the value for account_product.permission
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public void setPermission(Integer permission) {
		this.permission = permission;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account_product.account_id
	 * @return  the value of account_product.account_id
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public Long getAccount_id() {
		return account_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account_product.account_id
	 * @param account_id  the value for account_product.account_id
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public void setAccount_id(Long account_id) {
		this.account_id = account_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account_product.product_id
	 * @return  the value of account_product.product_id
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public Long getProduct_id() {
		return product_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account_product.product_id
	 * @param product_id  the value for account_product.product_id
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public void setProduct_id(Long product_id) {
		this.product_id = product_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account_product.created_by
	 * @return  the value of account_product.created_by
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public Long getCreated_by() {
		return created_by;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account_product.created_by
	 * @param created_by  the value for account_product.created_by
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public void setCreated_by(Long created_by) {
		this.created_by = created_by;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account_product.updated_by
	 * @return  the value of account_product.updated_by
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public Long getUpdated_by() {
		return updated_by;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account_product.updated_by
	 * @param updated_by  the value for account_product.updated_by
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public void setUpdated_by(Long updated_by) {
		this.updated_by = updated_by;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account_product.created_at
	 * @return  the value of account_product.created_at
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public Date getCreated_at() {
		return created_at;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account_product.created_at
	 * @param created_at  the value for account_product.created_at
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public void setCreated_at(Date created_at) {
		this.created_at = created_at;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account_product.updated_at
	 * @return  the value of account_product.updated_at
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public Date getUpdated_at() {
		return updated_at;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account_product.updated_at
	 * @param updated_at  the value for account_product.updated_at
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public void setUpdated_at(Date updated_at) {
		this.updated_at = updated_at;
	}
}