package work.tomosse.model.db;

import java.util.Date;

public class ColumnManage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_manage.id
     *
     * @mbg.generated Tue Nov 19 18:58:53 JST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_manage.product_id
     *
     * @mbg.generated Tue Nov 19 18:58:53 JST 2019
     */
    private Long product_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_manage.column_type
     *
     * @mbg.generated Tue Nov 19 18:58:53 JST 2019
     */
    private String column_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_manage.validation
     *
     * @mbg.generated Tue Nov 19 18:58:53 JST 2019
     */
    private String validation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_manage.created_by
     *
     * @mbg.generated Tue Nov 19 18:58:53 JST 2019
     */
    private Long created_by;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_manage.updated_by
     *
     * @mbg.generated Tue Nov 19 18:58:53 JST 2019
     */
    private Long updated_by;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_manage.created_at
     *
     * @mbg.generated Tue Nov 19 18:58:53 JST 2019
     */
    private Date created_at;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_manage.updated_at
     *
     * @mbg.generated Tue Nov 19 18:58:53 JST 2019
     */
    private Date updated_at;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_manage.id
     *
     * @return the value of column_manage.id
     *
     * @mbg.generated Tue Nov 19 18:58:53 JST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_manage.id
     *
     * @param id the value for column_manage.id
     *
     * @mbg.generated Tue Nov 19 18:58:53 JST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_manage.product_id
     *
     * @return the value of column_manage.product_id
     *
     * @mbg.generated Tue Nov 19 18:58:53 JST 2019
     */
    public Long getProduct_id() {
        return product_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_manage.product_id
     *
     * @param product_id the value for column_manage.product_id
     *
     * @mbg.generated Tue Nov 19 18:58:53 JST 2019
     */
    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_manage.column_type
     *
     * @return the value of column_manage.column_type
     *
     * @mbg.generated Tue Nov 19 18:58:53 JST 2019
     */
    public String getColumn_type() {
        return column_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_manage.column_type
     *
     * @param column_type the value for column_manage.column_type
     *
     * @mbg.generated Tue Nov 19 18:58:53 JST 2019
     */
    public void setColumn_type(String column_type) {
        this.column_type = column_type == null ? null : column_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_manage.validation
     *
     * @return the value of column_manage.validation
     *
     * @mbg.generated Tue Nov 19 18:58:53 JST 2019
     */
    public String getValidation() {
        return validation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_manage.validation
     *
     * @param validation the value for column_manage.validation
     *
     * @mbg.generated Tue Nov 19 18:58:53 JST 2019
     */
    public void setValidation(String validation) {
        this.validation = validation == null ? null : validation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_manage.created_by
     *
     * @return the value of column_manage.created_by
     *
     * @mbg.generated Tue Nov 19 18:58:53 JST 2019
     */
    public Long getCreated_by() {
        return created_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_manage.created_by
     *
     * @param created_by the value for column_manage.created_by
     *
     * @mbg.generated Tue Nov 19 18:58:53 JST 2019
     */
    public void setCreated_by(Long created_by) {
        this.created_by = created_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_manage.updated_by
     *
     * @return the value of column_manage.updated_by
     *
     * @mbg.generated Tue Nov 19 18:58:53 JST 2019
     */
    public Long getUpdated_by() {
        return updated_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_manage.updated_by
     *
     * @param updated_by the value for column_manage.updated_by
     *
     * @mbg.generated Tue Nov 19 18:58:53 JST 2019
     */
    public void setUpdated_by(Long updated_by) {
        this.updated_by = updated_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_manage.created_at
     *
     * @return the value of column_manage.created_at
     *
     * @mbg.generated Tue Nov 19 18:58:53 JST 2019
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_manage.created_at
     *
     * @param created_at the value for column_manage.created_at
     *
     * @mbg.generated Tue Nov 19 18:58:53 JST 2019
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_manage.updated_at
     *
     * @return the value of column_manage.updated_at
     *
     * @mbg.generated Tue Nov 19 18:58:53 JST 2019
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_manage.updated_at
     *
     * @param updated_at the value for column_manage.updated_at
     *
     * @mbg.generated Tue Nov 19 18:58:53 JST 2019
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }
}