package work.tomosse.model.db;

import java.util.Date;

public class ContentData {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_data.id
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_data.product_id
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	private Long product_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_data.created_by
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	private Long created_by;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_data.updated_by
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	private Long updated_by;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_data.created_at
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	private Date created_at;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_data.updated_at
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	private Date updated_at;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_data.id
	 * @return  the value of content_data.id
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_data.id
	 * @param id  the value for content_data.id
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_data.product_id
	 * @return  the value of content_data.product_id
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public Long getProduct_id() {
		return product_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_data.product_id
	 * @param product_id  the value for content_data.product_id
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public void setProduct_id(Long product_id) {
		this.product_id = product_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_data.created_by
	 * @return  the value of content_data.created_by
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public Long getCreated_by() {
		return created_by;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_data.created_by
	 * @param created_by  the value for content_data.created_by
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public void setCreated_by(Long created_by) {
		this.created_by = created_by;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_data.updated_by
	 * @return  the value of content_data.updated_by
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public Long getUpdated_by() {
		return updated_by;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_data.updated_by
	 * @param updated_by  the value for content_data.updated_by
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public void setUpdated_by(Long updated_by) {
		this.updated_by = updated_by;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_data.created_at
	 * @return  the value of content_data.created_at
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public Date getCreated_at() {
		return created_at;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_data.created_at
	 * @param created_at  the value for content_data.created_at
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public void setCreated_at(Date created_at) {
		this.created_at = created_at;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_data.updated_at
	 * @return  the value of content_data.updated_at
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public Date getUpdated_at() {
		return updated_at;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_data.updated_at
	 * @param updated_at  the value for content_data.updated_at
	 * @mbg.generated  Thu Nov 28 22:47:44 JST 2019
	 */
	public void setUpdated_at(Date updated_at) {
		this.updated_at = updated_at;
	}
}