package work.tomosse.model.db;

import java.util.Date;

public class Product {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.id
	 * @mbg.generated  Sun Dec 01 00:33:34 JST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.name
	 * @mbg.generated  Sun Dec 01 00:33:34 JST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.created_by
	 * @mbg.generated  Sun Dec 01 00:33:34 JST 2019
	 */
	private Long created_by;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.updated_by
	 * @mbg.generated  Sun Dec 01 00:33:34 JST 2019
	 */
	private Long updated_by;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.created_at
	 * @mbg.generated  Sun Dec 01 00:33:34 JST 2019
	 */
	private Date created_at;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.updated_at
	 * @mbg.generated  Sun Dec 01 00:33:34 JST 2019
	 */
	private Date updated_at;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.id
	 * @return  the value of product.id
	 * @mbg.generated  Sun Dec 01 00:33:34 JST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.id
	 * @param id  the value for product.id
	 * @mbg.generated  Sun Dec 01 00:33:34 JST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.name
	 * @return  the value of product.name
	 * @mbg.generated  Sun Dec 01 00:33:34 JST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.name
	 * @param name  the value for product.name
	 * @mbg.generated  Sun Dec 01 00:33:34 JST 2019
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.created_by
	 * @return  the value of product.created_by
	 * @mbg.generated  Sun Dec 01 00:33:34 JST 2019
	 */
	public Long getCreated_by() {
		return created_by;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.created_by
	 * @param created_by  the value for product.created_by
	 * @mbg.generated  Sun Dec 01 00:33:34 JST 2019
	 */
	public void setCreated_by(Long created_by) {
		this.created_by = created_by;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.updated_by
	 * @return  the value of product.updated_by
	 * @mbg.generated  Sun Dec 01 00:33:34 JST 2019
	 */
	public Long getUpdated_by() {
		return updated_by;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.updated_by
	 * @param updated_by  the value for product.updated_by
	 * @mbg.generated  Sun Dec 01 00:33:34 JST 2019
	 */
	public void setUpdated_by(Long updated_by) {
		this.updated_by = updated_by;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.created_at
	 * @return  the value of product.created_at
	 * @mbg.generated  Sun Dec 01 00:33:34 JST 2019
	 */
	public Date getCreated_at() {
		return created_at;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.created_at
	 * @param created_at  the value for product.created_at
	 * @mbg.generated  Sun Dec 01 00:33:34 JST 2019
	 */
	public void setCreated_at(Date created_at) {
		this.created_at = created_at;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.updated_at
	 * @return  the value of product.updated_at
	 * @mbg.generated  Sun Dec 01 00:33:34 JST 2019
	 */
	public Date getUpdated_at() {
		return updated_at;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.updated_at
	 * @param updated_at  the value for product.updated_at
	 * @mbg.generated  Sun Dec 01 00:33:34 JST 2019
	 */
	public void setUpdated_at(Date updated_at) {
		this.updated_at = updated_at;
	}
}