package work.tomosse.garage_house.model.db;

import java.util.Date;

public class ColumnValidation {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column column_validation.id
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column column_validation.column_manage_id
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	private Long columnManageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column column_validation.validate
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	private String validate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column column_validation.created_by
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	private Long createdBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column column_validation.updated_by
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	private Long updatedBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column column_validation.created_at
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column column_validation.updated_at
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column column_validation.id
	 * @return  the value of column_validation.id
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column column_validation.id
	 * @param id  the value for column_validation.id
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column column_validation.column_manage_id
	 * @return  the value of column_validation.column_manage_id
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public Long getColumnManageId() {
		return columnManageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column column_validation.column_manage_id
	 * @param columnManageId  the value for column_validation.column_manage_id
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public void setColumnManageId(Long columnManageId) {
		this.columnManageId = columnManageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column column_validation.validate
	 * @return  the value of column_validation.validate
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public String getValidate() {
		return validate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column column_validation.validate
	 * @param validate  the value for column_validation.validate
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public void setValidate(String validate) {
		this.validate = validate == null ? null : validate.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column column_validation.created_by
	 * @return  the value of column_validation.created_by
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public Long getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column column_validation.created_by
	 * @param createdBy  the value for column_validation.created_by
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column column_validation.updated_by
	 * @return  the value of column_validation.updated_by
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public Long getUpdatedBy() {
		return updatedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column column_validation.updated_by
	 * @param updatedBy  the value for column_validation.updated_by
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column column_validation.created_at
	 * @return  the value of column_validation.created_at
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column column_validation.created_at
	 * @param createdAt  the value for column_validation.created_at
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column column_validation.updated_at
	 * @return  the value of column_validation.updated_at
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column column_validation.updated_at
	 * @param updatedAt  the value for column_validation.updated_at
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}