package work.tomosse.garage_house.model.db;

import java.util.Date;

public class ContentData {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_data.id
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_data.product_id
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	private Long productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_data.created_by
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	private Long createdBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_data.updated_by
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	private Long updatedBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_data.created_at
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content_data.updated_at
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_data.id
	 * @return  the value of content_data.id
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_data.id
	 * @param id  the value for content_data.id
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_data.product_id
	 * @return  the value of content_data.product_id
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public Long getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_data.product_id
	 * @param productId  the value for content_data.product_id
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public void setProductId(Long productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_data.created_by
	 * @return  the value of content_data.created_by
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public Long getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_data.created_by
	 * @param createdBy  the value for content_data.created_by
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_data.updated_by
	 * @return  the value of content_data.updated_by
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public Long getUpdatedBy() {
		return updatedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_data.updated_by
	 * @param updatedBy  the value for content_data.updated_by
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_data.created_at
	 * @return  the value of content_data.created_at
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_data.created_at
	 * @param createdAt  the value for content_data.created_at
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content_data.updated_at
	 * @return  the value of content_data.updated_at
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content_data.updated_at
	 * @param updatedAt  the value for content_data.updated_at
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}