package work.tomosse.garage_house.model.db;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ContentExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table content
	 * @mbg.generated  Wed Dec 04 15:36:44 JST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table content
	 * @mbg.generated  Wed Dec 04 15:36:44 JST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table content
	 * @mbg.generated  Wed Dec 04 15:36:44 JST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Wed Dec 04 15:36:44 JST 2019
	 */
	public ContentExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Wed Dec 04 15:36:44 JST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Wed Dec 04 15:36:44 JST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Wed Dec 04 15:36:44 JST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Wed Dec 04 15:36:44 JST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Wed Dec 04 15:36:44 JST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Wed Dec 04 15:36:44 JST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Wed Dec 04 15:36:44 JST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Wed Dec 04 15:36:44 JST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Wed Dec 04 15:36:44 JST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Wed Dec 04 15:36:44 JST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table content
	 * @mbg.generated  Wed Dec 04 15:36:44 JST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andColumn_manage_idIsNull() {
			addCriterion("column_manage_id is null");
			return (Criteria) this;
		}

		public Criteria andColumn_manage_idIsNotNull() {
			addCriterion("column_manage_id is not null");
			return (Criteria) this;
		}

		public Criteria andColumn_manage_idEqualTo(Long value) {
			addCriterion("column_manage_id =", value, "column_manage_id");
			return (Criteria) this;
		}

		public Criteria andColumn_manage_idNotEqualTo(Long value) {
			addCriterion("column_manage_id <>", value, "column_manage_id");
			return (Criteria) this;
		}

		public Criteria andColumn_manage_idGreaterThan(Long value) {
			addCriterion("column_manage_id >", value, "column_manage_id");
			return (Criteria) this;
		}

		public Criteria andColumn_manage_idGreaterThanOrEqualTo(Long value) {
			addCriterion("column_manage_id >=", value, "column_manage_id");
			return (Criteria) this;
		}

		public Criteria andColumn_manage_idLessThan(Long value) {
			addCriterion("column_manage_id <", value, "column_manage_id");
			return (Criteria) this;
		}

		public Criteria andColumn_manage_idLessThanOrEqualTo(Long value) {
			addCriterion("column_manage_id <=", value, "column_manage_id");
			return (Criteria) this;
		}

		public Criteria andColumn_manage_idIn(List<Long> values) {
			addCriterion("column_manage_id in", values, "column_manage_id");
			return (Criteria) this;
		}

		public Criteria andColumn_manage_idNotIn(List<Long> values) {
			addCriterion("column_manage_id not in", values, "column_manage_id");
			return (Criteria) this;
		}

		public Criteria andColumn_manage_idBetween(Long value1, Long value2) {
			addCriterion("column_manage_id between", value1, value2, "column_manage_id");
			return (Criteria) this;
		}

		public Criteria andColumn_manage_idNotBetween(Long value1, Long value2) {
			addCriterion("column_manage_id not between", value1, value2, "column_manage_id");
			return (Criteria) this;
		}

		public Criteria andContent_data_idIsNull() {
			addCriterion("content_data_id is null");
			return (Criteria) this;
		}

		public Criteria andContent_data_idIsNotNull() {
			addCriterion("content_data_id is not null");
			return (Criteria) this;
		}

		public Criteria andContent_data_idEqualTo(Long value) {
			addCriterion("content_data_id =", value, "content_data_id");
			return (Criteria) this;
		}

		public Criteria andContent_data_idNotEqualTo(Long value) {
			addCriterion("content_data_id <>", value, "content_data_id");
			return (Criteria) this;
		}

		public Criteria andContent_data_idGreaterThan(Long value) {
			addCriterion("content_data_id >", value, "content_data_id");
			return (Criteria) this;
		}

		public Criteria andContent_data_idGreaterThanOrEqualTo(Long value) {
			addCriterion("content_data_id >=", value, "content_data_id");
			return (Criteria) this;
		}

		public Criteria andContent_data_idLessThan(Long value) {
			addCriterion("content_data_id <", value, "content_data_id");
			return (Criteria) this;
		}

		public Criteria andContent_data_idLessThanOrEqualTo(Long value) {
			addCriterion("content_data_id <=", value, "content_data_id");
			return (Criteria) this;
		}

		public Criteria andContent_data_idIn(List<Long> values) {
			addCriterion("content_data_id in", values, "content_data_id");
			return (Criteria) this;
		}

		public Criteria andContent_data_idNotIn(List<Long> values) {
			addCriterion("content_data_id not in", values, "content_data_id");
			return (Criteria) this;
		}

		public Criteria andContent_data_idBetween(Long value1, Long value2) {
			addCriterion("content_data_id between", value1, value2, "content_data_id");
			return (Criteria) this;
		}

		public Criteria andContent_data_idNotBetween(Long value1, Long value2) {
			addCriterion("content_data_id not between", value1, value2, "content_data_id");
			return (Criteria) this;
		}

		public Criteria andBodyIsNull() {
			addCriterion("body is null");
			return (Criteria) this;
		}

		public Criteria andBodyIsNotNull() {
			addCriterion("body is not null");
			return (Criteria) this;
		}

		public Criteria andBodyEqualTo(String value) {
			addCriterion("body =", value, "body");
			return (Criteria) this;
		}

		public Criteria andBodyNotEqualTo(String value) {
			addCriterion("body <>", value, "body");
			return (Criteria) this;
		}

		public Criteria andBodyGreaterThan(String value) {
			addCriterion("body >", value, "body");
			return (Criteria) this;
		}

		public Criteria andBodyGreaterThanOrEqualTo(String value) {
			addCriterion("body >=", value, "body");
			return (Criteria) this;
		}

		public Criteria andBodyLessThan(String value) {
			addCriterion("body <", value, "body");
			return (Criteria) this;
		}

		public Criteria andBodyLessThanOrEqualTo(String value) {
			addCriterion("body <=", value, "body");
			return (Criteria) this;
		}

		public Criteria andBodyLike(String value) {
			addCriterion("body like", value, "body");
			return (Criteria) this;
		}

		public Criteria andBodyNotLike(String value) {
			addCriterion("body not like", value, "body");
			return (Criteria) this;
		}

		public Criteria andBodyIn(List<String> values) {
			addCriterion("body in", values, "body");
			return (Criteria) this;
		}

		public Criteria andBodyNotIn(List<String> values) {
			addCriterion("body not in", values, "body");
			return (Criteria) this;
		}

		public Criteria andBodyBetween(String value1, String value2) {
			addCriterion("body between", value1, value2, "body");
			return (Criteria) this;
		}

		public Criteria andBodyNotBetween(String value1, String value2) {
			addCriterion("body not between", value1, value2, "body");
			return (Criteria) this;
		}

		public Criteria andCreated_byIsNull() {
			addCriterion("created_by is null");
			return (Criteria) this;
		}

		public Criteria andCreated_byIsNotNull() {
			addCriterion("created_by is not null");
			return (Criteria) this;
		}

		public Criteria andCreated_byEqualTo(Long value) {
			addCriterion("created_by =", value, "created_by");
			return (Criteria) this;
		}

		public Criteria andCreated_byNotEqualTo(Long value) {
			addCriterion("created_by <>", value, "created_by");
			return (Criteria) this;
		}

		public Criteria andCreated_byGreaterThan(Long value) {
			addCriterion("created_by >", value, "created_by");
			return (Criteria) this;
		}

		public Criteria andCreated_byGreaterThanOrEqualTo(Long value) {
			addCriterion("created_by >=", value, "created_by");
			return (Criteria) this;
		}

		public Criteria andCreated_byLessThan(Long value) {
			addCriterion("created_by <", value, "created_by");
			return (Criteria) this;
		}

		public Criteria andCreated_byLessThanOrEqualTo(Long value) {
			addCriterion("created_by <=", value, "created_by");
			return (Criteria) this;
		}

		public Criteria andCreated_byIn(List<Long> values) {
			addCriterion("created_by in", values, "created_by");
			return (Criteria) this;
		}

		public Criteria andCreated_byNotIn(List<Long> values) {
			addCriterion("created_by not in", values, "created_by");
			return (Criteria) this;
		}

		public Criteria andCreated_byBetween(Long value1, Long value2) {
			addCriterion("created_by between", value1, value2, "created_by");
			return (Criteria) this;
		}

		public Criteria andCreated_byNotBetween(Long value1, Long value2) {
			addCriterion("created_by not between", value1, value2, "created_by");
			return (Criteria) this;
		}

		public Criteria andUpdated_byIsNull() {
			addCriterion("updated_by is null");
			return (Criteria) this;
		}

		public Criteria andUpdated_byIsNotNull() {
			addCriterion("updated_by is not null");
			return (Criteria) this;
		}

		public Criteria andUpdated_byEqualTo(Long value) {
			addCriterion("updated_by =", value, "updated_by");
			return (Criteria) this;
		}

		public Criteria andUpdated_byNotEqualTo(Long value) {
			addCriterion("updated_by <>", value, "updated_by");
			return (Criteria) this;
		}

		public Criteria andUpdated_byGreaterThan(Long value) {
			addCriterion("updated_by >", value, "updated_by");
			return (Criteria) this;
		}

		public Criteria andUpdated_byGreaterThanOrEqualTo(Long value) {
			addCriterion("updated_by >=", value, "updated_by");
			return (Criteria) this;
		}

		public Criteria andUpdated_byLessThan(Long value) {
			addCriterion("updated_by <", value, "updated_by");
			return (Criteria) this;
		}

		public Criteria andUpdated_byLessThanOrEqualTo(Long value) {
			addCriterion("updated_by <=", value, "updated_by");
			return (Criteria) this;
		}

		public Criteria andUpdated_byIn(List<Long> values) {
			addCriterion("updated_by in", values, "updated_by");
			return (Criteria) this;
		}

		public Criteria andUpdated_byNotIn(List<Long> values) {
			addCriterion("updated_by not in", values, "updated_by");
			return (Criteria) this;
		}

		public Criteria andUpdated_byBetween(Long value1, Long value2) {
			addCriterion("updated_by between", value1, value2, "updated_by");
			return (Criteria) this;
		}

		public Criteria andUpdated_byNotBetween(Long value1, Long value2) {
			addCriterion("updated_by not between", value1, value2, "updated_by");
			return (Criteria) this;
		}

		public Criteria andCreated_atIsNull() {
			addCriterion("created_at is null");
			return (Criteria) this;
		}

		public Criteria andCreated_atIsNotNull() {
			addCriterion("created_at is not null");
			return (Criteria) this;
		}

		public Criteria andCreated_atEqualTo(Date value) {
			addCriterion("created_at =", value, "created_at");
			return (Criteria) this;
		}

		public Criteria andCreated_atNotEqualTo(Date value) {
			addCriterion("created_at <>", value, "created_at");
			return (Criteria) this;
		}

		public Criteria andCreated_atGreaterThan(Date value) {
			addCriterion("created_at >", value, "created_at");
			return (Criteria) this;
		}

		public Criteria andCreated_atGreaterThanOrEqualTo(Date value) {
			addCriterion("created_at >=", value, "created_at");
			return (Criteria) this;
		}

		public Criteria andCreated_atLessThan(Date value) {
			addCriterion("created_at <", value, "created_at");
			return (Criteria) this;
		}

		public Criteria andCreated_atLessThanOrEqualTo(Date value) {
			addCriterion("created_at <=", value, "created_at");
			return (Criteria) this;
		}

		public Criteria andCreated_atIn(List<Date> values) {
			addCriterion("created_at in", values, "created_at");
			return (Criteria) this;
		}

		public Criteria andCreated_atNotIn(List<Date> values) {
			addCriterion("created_at not in", values, "created_at");
			return (Criteria) this;
		}

		public Criteria andCreated_atBetween(Date value1, Date value2) {
			addCriterion("created_at between", value1, value2, "created_at");
			return (Criteria) this;
		}

		public Criteria andCreated_atNotBetween(Date value1, Date value2) {
			addCriterion("created_at not between", value1, value2, "created_at");
			return (Criteria) this;
		}

		public Criteria andUpdated_atIsNull() {
			addCriterion("updated_at is null");
			return (Criteria) this;
		}

		public Criteria andUpdated_atIsNotNull() {
			addCriterion("updated_at is not null");
			return (Criteria) this;
		}

		public Criteria andUpdated_atEqualTo(Date value) {
			addCriterion("updated_at =", value, "updated_at");
			return (Criteria) this;
		}

		public Criteria andUpdated_atNotEqualTo(Date value) {
			addCriterion("updated_at <>", value, "updated_at");
			return (Criteria) this;
		}

		public Criteria andUpdated_atGreaterThan(Date value) {
			addCriterion("updated_at >", value, "updated_at");
			return (Criteria) this;
		}

		public Criteria andUpdated_atGreaterThanOrEqualTo(Date value) {
			addCriterion("updated_at >=", value, "updated_at");
			return (Criteria) this;
		}

		public Criteria andUpdated_atLessThan(Date value) {
			addCriterion("updated_at <", value, "updated_at");
			return (Criteria) this;
		}

		public Criteria andUpdated_atLessThanOrEqualTo(Date value) {
			addCriterion("updated_at <=", value, "updated_at");
			return (Criteria) this;
		}

		public Criteria andUpdated_atIn(List<Date> values) {
			addCriterion("updated_at in", values, "updated_at");
			return (Criteria) this;
		}

		public Criteria andUpdated_atNotIn(List<Date> values) {
			addCriterion("updated_at not in", values, "updated_at");
			return (Criteria) this;
		}

		public Criteria andUpdated_atBetween(Date value1, Date value2) {
			addCriterion("updated_at between", value1, value2, "updated_at");
			return (Criteria) this;
		}

		public Criteria andUpdated_atNotBetween(Date value1, Date value2) {
			addCriterion("updated_at not between", value1, value2, "updated_at");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table content
	 * @mbg.generated  Wed Dec 04 15:36:44 JST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table content
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 19 18:58:53 JST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}