package work.tomosse.garage_house.model.db;

import java.util.Date;

public class Content {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content.id
	 * @mbg.generated  Thu Dec 05 13:24:26 JST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content.column_manage_id
	 * @mbg.generated  Thu Dec 05 13:24:26 JST 2019
	 */
	private Long columnManageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content.content_data_id
	 * @mbg.generated  Thu Dec 05 13:24:26 JST 2019
	 */
	private Long contentDataId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content.body
	 * @mbg.generated  Thu Dec 05 13:24:26 JST 2019
	 */
	private String body;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content.created_by
	 * @mbg.generated  Thu Dec 05 13:24:26 JST 2019
	 */
	private Long createdBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content.updated_by
	 * @mbg.generated  Thu Dec 05 13:24:26 JST 2019
	 */
	private Long updatedBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content.created_at
	 * @mbg.generated  Thu Dec 05 13:24:26 JST 2019
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content.updated_at
	 * @mbg.generated  Thu Dec 05 13:24:26 JST 2019
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content.id
	 * @return  the value of content.id
	 * @mbg.generated  Thu Dec 05 13:24:26 JST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content.id
	 * @param id  the value for content.id
	 * @mbg.generated  Thu Dec 05 13:24:26 JST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content.column_manage_id
	 * @return  the value of content.column_manage_id
	 * @mbg.generated  Thu Dec 05 13:24:26 JST 2019
	 */
	public Long getColumnManageId() {
		return columnManageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content.column_manage_id
	 * @param columnManageId  the value for content.column_manage_id
	 * @mbg.generated  Thu Dec 05 13:24:26 JST 2019
	 */
	public void setColumnManageId(Long columnManageId) {
		this.columnManageId = columnManageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content.content_data_id
	 * @return  the value of content.content_data_id
	 * @mbg.generated  Thu Dec 05 13:24:26 JST 2019
	 */
	public Long getContentDataId() {
		return contentDataId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content.content_data_id
	 * @param contentDataId  the value for content.content_data_id
	 * @mbg.generated  Thu Dec 05 13:24:26 JST 2019
	 */
	public void setContentDataId(Long contentDataId) {
		this.contentDataId = contentDataId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content.body
	 * @return  the value of content.body
	 * @mbg.generated  Thu Dec 05 13:24:26 JST 2019
	 */
	public String getBody() {
		return body;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content.body
	 * @param body  the value for content.body
	 * @mbg.generated  Thu Dec 05 13:24:26 JST 2019
	 */
	public void setBody(String body) {
		this.body = body == null ? null : body.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content.created_by
	 * @return  the value of content.created_by
	 * @mbg.generated  Thu Dec 05 13:24:26 JST 2019
	 */
	public Long getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content.created_by
	 * @param createdBy  the value for content.created_by
	 * @mbg.generated  Thu Dec 05 13:24:26 JST 2019
	 */
	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content.updated_by
	 * @return  the value of content.updated_by
	 * @mbg.generated  Thu Dec 05 13:24:26 JST 2019
	 */
	public Long getUpdatedBy() {
		return updatedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content.updated_by
	 * @param updatedBy  the value for content.updated_by
	 * @mbg.generated  Thu Dec 05 13:24:26 JST 2019
	 */
	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content.created_at
	 * @return  the value of content.created_at
	 * @mbg.generated  Thu Dec 05 13:24:26 JST 2019
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content.created_at
	 * @param createdAt  the value for content.created_at
	 * @mbg.generated  Thu Dec 05 13:24:26 JST 2019
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content.updated_at
	 * @return  the value of content.updated_at
	 * @mbg.generated  Thu Dec 05 13:24:26 JST 2019
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content.updated_at
	 * @param updatedAt  the value for content.updated_at
	 * @mbg.generated  Thu Dec 05 13:24:26 JST 2019
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}