package work.tomosse.garage_house.model.db;

import java.util.Date;

public class Product {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.id
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.name
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.created_by
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	private Long createdBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.updated_by
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	private Long updatedBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.created_at
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.updated_at
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.id
	 * @return  the value of product.id
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.id
	 * @param id  the value for product.id
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.name
	 * @return  the value of product.name
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.name
	 * @param name  the value for product.name
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.created_by
	 * @return  the value of product.created_by
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public Long getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.created_by
	 * @param createdBy  the value for product.created_by
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.updated_by
	 * @return  the value of product.updated_by
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public Long getUpdatedBy() {
		return updatedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.updated_by
	 * @param updatedBy  the value for product.updated_by
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.created_at
	 * @return  the value of product.created_at
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.created_at
	 * @param createdAt  the value for product.created_at
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.updated_at
	 * @return  the value of product.updated_at
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.updated_at
	 * @param updatedAt  the value for product.updated_at
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}