package work.tomosse.garage_house.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import work.tomosse.garage_house.model.db.AccountProduct;
import work.tomosse.garage_house.model.db.AccountProductExample;

@Mapper
public interface AccountProductMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_product
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	long countByExample(AccountProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_product
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	int deleteByExample(AccountProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_product
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_product
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	int insert(AccountProduct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_product
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	int insertSelective(AccountProduct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_product
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	List<AccountProduct> selectByExample(AccountProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_product
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	AccountProduct selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_product
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	int updateByExampleSelective(@Param("record") AccountProduct record,
			@Param("example") AccountProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_product
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	int updateByExample(@Param("record") AccountProduct record, @Param("example") AccountProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_product
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	int updateByPrimaryKeySelective(AccountProduct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_product
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	int updateByPrimaryKey(AccountProduct record);
}