package work.tomosse.garage_house.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import work.tomosse.garage_house.model.db.ColumnValidation;
import work.tomosse.garage_house.model.db.ColumnValidationExample;

public interface ColumnValidationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table column_validation
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	long countByExample(ColumnValidationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table column_validation
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	int deleteByExample(ColumnValidationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table column_validation
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table column_validation
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	int insert(ColumnValidation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table column_validation
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	int insertSelective(ColumnValidation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table column_validation
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	List<ColumnValidation> selectByExample(ColumnValidationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table column_validation
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	ColumnValidation selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table column_validation
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	int updateByExampleSelective(@Param("record") ColumnValidation record,
			@Param("example") ColumnValidationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table column_validation
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	int updateByExample(@Param("record") ColumnValidation record, @Param("example") ColumnValidationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table column_validation
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	int updateByPrimaryKeySelective(ColumnValidation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table column_validation
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	int updateByPrimaryKey(ColumnValidation record);
}