package work.tomosse.garage_house.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import work.tomosse.garage_house.model.db.Content;
import work.tomosse.garage_house.model.db.ContentExample;

@Mapper
public interface ContentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	long countByExample(ContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	int deleteByExample(ContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	int insert(Content record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	int insertSelective(Content record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	List<Content> selectByExample(ContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	Content selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	int updateByExampleSelective(@Param("record") Content record, @Param("example") ContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	int updateByExample(@Param("record") Content record, @Param("example") ContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	int updateByPrimaryKeySelective(Content record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Thu Dec 05 15:40:54 JST 2019
	 */
	int updateByPrimaryKey(Content record);
}