package work.tomosse.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import work.tomosse.model.db.ColumnManage;
import work.tomosse.model.db.ColumnManageExample;

@Mapper
public interface ColumnManageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table column_manage
	 * @mbg.generated  Sun Dec 01 00:33:34 JST 2019
	 */
	long countByExample(ColumnManageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table column_manage
	 * @mbg.generated  Sun Dec 01 00:33:34 JST 2019
	 */
	int deleteByExample(ColumnManageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table column_manage
	 * @mbg.generated  Sun Dec 01 00:33:34 JST 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table column_manage
	 * @mbg.generated  Sun Dec 01 00:33:34 JST 2019
	 */
	int insert(ColumnManage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table column_manage
	 * @mbg.generated  Sun Dec 01 00:33:34 JST 2019
	 */
	int insertSelective(ColumnManage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table column_manage
	 * @mbg.generated  Sun Dec 01 00:33:34 JST 2019
	 */
	List<ColumnManage> selectByExample(ColumnManageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table column_manage
	 * @mbg.generated  Sun Dec 01 00:33:34 JST 2019
	 */
	ColumnManage selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table column_manage
	 * @mbg.generated  Sun Dec 01 00:33:34 JST 2019
	 */
	int updateByExampleSelective(@Param("record") ColumnManage record, @Param("example") ColumnManageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table column_manage
	 * @mbg.generated  Sun Dec 01 00:33:34 JST 2019
	 */
	int updateByExample(@Param("record") ColumnManage record, @Param("example") ColumnManageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table column_manage
	 * @mbg.generated  Sun Dec 01 00:33:34 JST 2019
	 */
	int updateByPrimaryKeySelective(ColumnManage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table column_manage
	 * @mbg.generated  Sun Dec 01 00:33:34 JST 2019
	 */
	int updateByPrimaryKey(ColumnManage record);
}