package work.tomosse.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import work.tomosse.model.db.ContentData;
import work.tomosse.model.db.ContentDataExample;

public interface ContentDataMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content_data
	 * @mbg.generated  Tue Nov 19 18:58:53 JST 2019
	 */
	long countByExample(ContentDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content_data
	 * @mbg.generated  Tue Nov 19 18:58:53 JST 2019
	 */
	int deleteByExample(ContentDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content_data
	 * @mbg.generated  Tue Nov 19 18:58:53 JST 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content_data
	 * @mbg.generated  Tue Nov 19 18:58:53 JST 2019
	 */
	int insert(ContentData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content_data
	 * @mbg.generated  Tue Nov 19 18:58:53 JST 2019
	 */
	int insertSelective(ContentData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content_data
	 * @mbg.generated  Tue Nov 19 18:58:53 JST 2019
	 */
	List<ContentData> selectByExample(ContentDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content_data
	 * @mbg.generated  Tue Nov 19 18:58:53 JST 2019
	 */
	ContentData selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content_data
	 * @mbg.generated  Tue Nov 19 18:58:53 JST 2019
	 */
	int updateByExampleSelective(@Param("record") ContentData record, @Param("example") ContentDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content_data
	 * @mbg.generated  Tue Nov 19 18:58:53 JST 2019
	 */
	int updateByExample(@Param("record") ContentData record, @Param("example") ContentDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content_data
	 * @mbg.generated  Tue Nov 19 18:58:53 JST 2019
	 */
	int updateByPrimaryKeySelective(ContentData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content_data
	 * @mbg.generated  Tue Nov 19 18:58:53 JST 2019
	 */
	int updateByPrimaryKey(ContentData record);
}