package work.tomosse.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import work.tomosse.model.db.Content;
import work.tomosse.model.db.ContentExample;

public interface ContentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Tue Nov 19 18:58:53 JST 2019
	 */
	long countByExample(ContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Tue Nov 19 18:58:53 JST 2019
	 */
	int deleteByExample(ContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Tue Nov 19 18:58:53 JST 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Tue Nov 19 18:58:53 JST 2019
	 */
	int insert(Content record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Tue Nov 19 18:58:53 JST 2019
	 */
	int insertSelective(Content record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Tue Nov 19 18:58:53 JST 2019
	 */
	List<Content> selectByExampleWithBLOBs(ContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Tue Nov 19 18:58:53 JST 2019
	 */
	List<Content> selectByExample(ContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Tue Nov 19 18:58:53 JST 2019
	 */
	Content selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Tue Nov 19 18:58:53 JST 2019
	 */
	int updateByExampleSelective(@Param("record") Content record, @Param("example") ContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Tue Nov 19 18:58:53 JST 2019
	 */
	int updateByExampleWithBLOBs(@Param("record") Content record, @Param("example") ContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Tue Nov 19 18:58:53 JST 2019
	 */
	int updateByExample(@Param("record") Content record, @Param("example") ContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Tue Nov 19 18:58:53 JST 2019
	 */
	int updateByPrimaryKeySelective(Content record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Tue Nov 19 18:58:53 JST 2019
	 */
	int updateByPrimaryKeyWithBLOBs(Content record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table content
	 * @mbg.generated  Tue Nov 19 18:58:53 JST 2019
	 */
	int updateByPrimaryKey(Content record);
}